### ISSUE TITLE
a7a82623

### ISSUE THREAD

**Issue by shilohd** [best-practice-and-impact/CARS-2#1]
Hashed final dataset (first 8 characters). 

Method (Python 3):

> import hashlib
> 
> file = open("lfilename.csv")
> read_file = file.read()
> 
> sha1_hash = hashlib.sha1(read_file.encode("utf-8"))
> print(sha1_hash.hexdigest())

**Comment by alexander-newton** [comment]
a7a82623 was my hash...

**Comment by shilohd** [comment]
Amended issue name with correct hash

**Comment by alexander-newton** [comment]
I'm fine with this dataset. Let's use a7a82623 as our dataset going forwards.
